---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"source.toolkit.fluxcd.io/v1beta1","kind":"GitRepository","metadata":{"annotations":{},"name":"flux-system","namespace":"flux-system"},"spec":{"gitImplementation":"libgit2","interval":"1m0s","ref":{"branch":"sandbox"},"secretRef":{"name":"flux-system"},"url":"https://github.com/ssakuh/flux-cd-repo"}}
  name: flux-system
  namespace: flux-system
spec:
  gitImplementation: libgit2
  interval: 1m0s
  ref:
    branch: sandbox
  secretRef:
    name: flux-system
  timeout: 1m0s
  url: https://github.com/ssakuh/flux-cd-repo

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kustomize.toolkit.fluxcd.io/v1beta2","kind":"Kustomization","metadata":{"annotations":{},"name":"flux-system","namespace":"flux-system"},"spec":{"interval":"10m0s","path":"./clusters/","prune":true,"sourceRef":{"kind":"GitRepository","name":"flux-system"}}}
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

